### ISSUE TITLE
Redirect home page to /berlin-2016/

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/viewsourceconf#106]
Redirect viewsourceconf.org/ to viewsourceconf.org/berlin-2016/

**Comment by stephaniehobson** [comment]
If you need context and I'm not around @hoosteeno is in earlier and also in the know.

**Comment by jgmize** [comment]
3498374  is deployed to stage and the following urls are all redirecting as expected:
https://viewsourceconf-stage.us-west.moz.works
https://viewsourceconf-stage.us-west.moz.works/
https://viewsourceconf-stage.us-west.moz.works/index.html

**Comment by jgmize** [comment]
deployed in tag [2016-07-19](https://github.com/mdn/viewsourceconf/releases/tag/2016-07-19) and verified the following are now redirecting as expected:
https://viewsourceconf.org
https://viewsourceconf.org/
https://viewsourceconf.org/index.html

Also verified that http->https redirects are still working as well:
http://viewsourceconf.org
http://viewsourceconf.org/
http://viewsourceconf.org/index.html

**Comment by stephaniehobson** [comment]
Awesomesaurus. Thank you :)
