### ISSUE TITLE
Add pictures for all talks/sessions

### ISSUE THREAD

**Issue by autonome** [mdn/viewsourceconf#130]
Right now the schedule looks a bit barren because many of the talks and sessions don't have any picture associated with it.

For Rust, we could add the Rust logo and for the VR workshops we could add the A-Frame logo, and that alone would brighten things up a bit.

**Comment by stephaniehobson** [comment]
All of the speaker photos are up and the design was altered to remove the space for a photo for discussion groups and demos which don't have photos.

Too bad we didn't have time to find photos for the discussion groups they're definitely a bit of a wall of text right now :(
