### ISSUE TITLE
Stage deploy failing with "Internal Server Error"

### ISSUE THREAD

**Issue by hoosteeno** [mdn/viewsourceconf#132]
Staging deploys are failing:

https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_stage/224/console

```
deis pull viewsourceconf-stage:9a76825 -a viewsourceconf-stage
Creating build... ...o...o...o...o...o...o...o...o...o...o...o...o...Error: 
500 INTERNAL SERVER ERROR
<h1>Server Error (500)</h1>

make: *** [deis-pull-private] Error 1
Build step 'Execute shell' marked build as failure
```

/cc @jgmize

**Comment by jgmize** [comment]
[Fixed](https://github.com/mozilla/ee-infra-jenkins/issues/11)and [deployed](https://ci.us-west.moz.works/view/viewsourceconf/job/viewsourceconf_deploy_stage/225/).
