### ISSUE TITLE
Prod deploys failing

### ISSUE THREAD

**Issue by hoosteeno** [mdn/viewsourceconf#175]
https://ci.us-west.moz.works/job/viewsourceconf_deploy_prod_us_west/47/console

[workspace] $ /bin/sh -xe /tmp/hudson6721793743499051441.sh
+ git describe --abbrev=0 --tags
+ export GIT_COMMIT=2016-09-12~0
+ make deis-pull-private
docker tag -f quay.io/mozmar/viewsourceconf\:6faae48 127.0.0.1:5001/viewsourceconf-prod\:6faae48
Error response from daemon: could not find image: no such id: quay.io/mozmar/viewsourceconf:6faae48
make: *** [push-private-registry] Error 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by jgmize** [comment]
I pulled the latest master, ran ./tag-release.sh --push and the latest master is in prod now. It looks like you may have tagged the ancestor of the latest master, prior to it being merged. This reveals an assumption in the shell script that you are always tagging the latest commit in the master branch.

**Comment by jgmize** [comment]
@hoosteeno based on our IRC conversation I'm going to go ahead and assume that the limitation of only being able to automatically trigger a successful deploy by tagging the latest commit of the master branch is acceptable and close this out. Rollbacks are possible via the deis CLI if necessary.

**Comment by hoosteeno** [comment]
Josh, tagging the latest commit for deploy is perfectly fine. Thanks for quick work here.
