### ISSUE TITLE
Create new page - https://viewsourceconf.org/london-2017/

### ISSUE THREAD

**Issue by ejregithub** [mdn/viewsourceconf#192]
Request to create new page - https://viewsourceconf.org/london-2017/

Please let me know if any further information is required.

**Comment by stephaniehobson** [comment]
@ejregithub Any text for that page or are you thinking all black?

**Comment by ejregithub** [comment]
I'm going to differ to Ali and Sandra. Will ping in email.  Ideally we lead with minimal copy about the London 2017 event and the URL to registration.

**Comment by stephaniehobson** [comment]
Done a while ago but only closing the issue now.

**Comment by ejregithub** [comment]
That page looks great!
