### ISSUE TITLE
Performance degredation after switching from nginx containers in k8s to s3+cloudfront

### ISSUE THREAD

**Issue by jgmize** [mdn/viewsourceconf#198]
Quoth @stephaniehobson:

> We seem to have back slid a bit in some of the performance ranking tools.

https://developers.google.com/speed/pagespeed/insights/?url=viewsourceconf.org

> We had over 90 / 100 last year when the site launched!

> I need to make a few changes too but could you tell me the best way to get help with these from your end? Git hub issues? On the ViewSourceConf repo?

- Setting a expiration
- gzipping
- CSP

> The definitions are all in the nginx files but I guess we are not using those anymore?

**Comment by jgmize** [comment]
Quoth @metadave:
```
We're using a lot of defaults, and Cloudfront has tons of switches to flip. I strongly prefer to stay on Cloudfront/S3 and experiment with settings to improve performance. What we find can be used on our other static sites as well.
```

**Comment by jgmize** [comment]
While we can always roll back to [nginx containers](https://github.com/mdn/viewsourceconf/blob/master/nginx.conf) I think tweaking the cloudfront config makes more sense. Let's see if we can get *better* than 90/100 :)

**Comment by stephaniehobson** [comment]
Looks like we have gzipping now, thanks :)

The far-future expiry date seems really difficult to achieve with Cloudfront. It can only be done [one at a time](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationAddingHeadersInS3). People are [writing scripts](http://www.laurencegellert.com/2012/07/how-to-set-the-expires-and-cache-control-headers-for-all-objects-in-an-aws-s3-bucket-with-a-php-script/) and using [3rd party tools](https://serverfault.com/questions/464416/using-amazon-s3-and-cloudfront-what-is-the-best-way-to-set-expires-headers-and-c). This seems like a real failing of the platform as a web host IMHO.

We don't want it on all files so a scripted solution would want to match our old nginx config:
```
location ~* \.(?:css|gif|ico|jpe?g|js|png|svg|ttf|woff2?)$ {
            expires max;
            add_header Cache-Control "public";
        }
```

**Comment by jgmize** [comment]
tracking switch back to nginx in #211
