### ISSUE TITLE
Can we remove nginx files?

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/viewsourceconf#207]
If we're rolling forward with the S3/Cloudfront setup should we remove the nginx config files?

Is there anything in the readme that needs to be updated to reflect that?

**Comment by jgmize** [comment]
The nginx files can still be used for local development, and based on the discussion in https://github.com/mozmeao/infra/issues/391 we may want to reconsider the s3+cloudfront (+lambda?) approach and switch back to nginx containers deployed via k8s.

**Comment by jgmize** [comment]
see also https://github.com/mdn/viewsourceconf/issues/209#issuecomment-323176181
