### ISSUE TITLE
Some users being redirected to /berlin-2016/

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/viewsourceconf#209]
I think this is only happening to users who previously visited viewsourceconf.org but I havn't been able to find anyone to confirm this.

**Comment by stephaniehobson** [comment]
It's affecting new users too :(

**Comment by jgmize** [comment]
Fixed this by restoring the metadata-based redirect that I had set up previously. Apparently whenever we deploy the site s3 was losing that metadata. Based on this and other issues, I'm going to roll the site back to the nginx + k8s deployments we were using before we switched to s3+cloudfront

**Comment by jgmize** [comment]
Here's what's happening now:
```
$ curl -I https://viewsourceconf.org
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Connection: keep-alive
Date: Thu, 17 Aug 2017 19:23:45 GMT
Location: https://viewsourceconf.org/london-2017/
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 1e0f6d91fb358639e6808cb6d2638da0.cloudfront.net (CloudFront)
X-Amz-Cf-Id: s77oPky6zmB_F6VIF6INWzS25N8onf4GPTsQbpNPr2QAlMmk8obHPg==
```

**Comment by jgmize** [comment]
tracking switch back to nginx in #211
