### ISSUE TITLE
Update/Replace unmaintained and out-of-date packages

### ISSUE THREAD

**Issue by Faeranne** [mdn/viewsourceconf#214]
Several NPM packages are either deprecated or unmaintained.

- [ ] `npm WARN deprecated swig@1.4.2: This package is no longer maintained`
- [ ] `npm WARN deprecated metalsmith-uglify@1.5.2: This module is no longer being maintained. Please reach out to package author if you wish to take over maintenance.`
- [x] `npm WARN deprecated nopter@0.3.0: try optionator`
- [x] `npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
- [x] `npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'`
- [x] `npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'`
- [x] `npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.`
- [x] `npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade`
- [x] `npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

The following packages are either out-of-date or unmaintained, but not marked by NPM.
- [ ] `broken-link-checker` uses `nopter`, and an open issue is available at stevenvachon/broken-link-checker#84
- [ ] `mocha` uses `to-iso-string`, `metalsmith-data-markdown`, and `jade`, and can be updated to 3.5.0
- [ ] `metalsmith-data-markdown` uses `CSSselect` and `CSSwhat`, and is abandoned
- [ ] Several metalsmith plugins use minimatch@0.2.14.

**Comment by mrmakeit** [comment]
`metalsmith-data-markdown` Is not deprecated, but was last updated on Oct 29, 2014, and is using the deprecated `CSSselect` and `CSSwhat`
