### ISSUE TITLE
Code of conduct link points to 2016/berlin event

### ISSUE THREAD

**Issue by alexgibson** [mdn/viewsourceconf#222]
After registering for the 2017 London event, the code of conduct link points to the old event:

<img width="907" alt="screen shot 2017-09-04 at 15 53 03" src="https://user-images.githubusercontent.com/400117/30031416-2da484be-9189-11e7-8ae8-aae7423db43b.png">

The link opens: https://viewsourceconf.org/berlin-2016/code-of-conduct/

It should be: https://viewsourceconf.org/london-2017/code-of-conduct/

**Comment by stephaniehobson** [comment]
This is a problem on the registration site ti.to so I can't fix it with edits on this repo. I've reported it to the right people and will keep this issue open until it's reported fixed.

Thanks for reporting it. And thank you for reading the CoC :)

**Comment by stephaniehobson** [comment]
Should be fixed now.
