### ISSUE TITLE
Service Worker is 404

### ISSUE THREAD

**Issue by alexgibson** [mdn/viewsourceconf#237]
I think I've found an error with our viewsource site:

I was trying to figure out why [this report](http://www.webpagetest.org/results.php?test=180306_RR_1b1bd17d856dd6e469db3d78b4e78392) wasn't returning all the data I expected and it looks like the [service worker file](https://viewsourceconf.org/worker.js) is 404:

```
"Failed to register/update a ServiceWorker for scope ‘https://viewsourceconf.org/’: Load failed with status 404 for script ‘https://viewsourceconf.org/worker.js’."
```

Unrelated, I also see "Load denied by X-Frame-Options" resulting in some content not appearing: 

```
Load denied by X-Frame-Options: https://air.mozilla.org/oidc/callback/?code=pIRH5679bVcvFBCM&state=qd0Fup7KrWFb9dYaOB6B5w9Plw0zmdlr does not permit framing."
```

**Comment by stephaniehobson** [comment]
This site doesn't have a service worker anymore, why is it expecting one?

**Comment by stephaniehobson** [comment]
I created a new issue for the Air Mozilla stuff (issue #238)

**Comment by alexgibson** [comment]
> This site doesn't have a service worker anymore, why is it expecting one?

It could be that my local browsers still have that service worker registered?

**Comment by alexgibson** [comment]
After a hard refresh of the home page, this error has not gone away. It could still be there for others though? As far as I understand it, removing a SW file may not be enough to unregister it, for those who have it active already. 

Some interesting reading: https://redfin.engineering/service-workers-break-the-browsers-refresh-button-by-default-here-s-why-56f9417694

**Comment by alexgibson** [comment]
Hmm, I still see this error in Chrome even after a hard refresh. I also tried closing the tab, and restarting the browser.

```
Error parsing header X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube: insecure reporting URL for secure page at character position 22. The default protections will be applied.
A bad HTTP response code (404) was received when fetching the script.
/worker.js Failed to load resource: net::ERR_INVALID_RESPONSE
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
```

**Comment by alexgibson** [comment]
The code to register the SW still seems to be in the repo: https://github.com/mdn/viewsourceconf/blob/master/source/js/00_global.js#L9-L13

**Comment by alexgibson** [comment]
I took at stab at fixing this in https://github.com/mdn/viewsourceconf/pull/239
