### ISSUE TITLE
Air Mozilla error

### ISSUE THREAD

**Issue by stephaniehobson** [mdn/viewsourceconf#238]
From issue #237 

> I also see "Load denied by X-Frame-Options" resulting in some content not appearing: 

```
Load denied by X-Frame-Options: https://air.mozilla.org/oidc/callback/?code=pIRH5679bVcvFBCM&state=qd0Fup7KrWFb9dYaOB6B5w9Plw0zmdlr does not permit framing."
```

**Comment by stephaniehobson** [comment]
The content appears for me and I don't see the error. Browser and OS?

**Comment by alexgibson** [comment]
> The content appears for me and I don't see the error. Browser and OS?

I was seeing this on both Firefox Nightly and Chrome, but it disappeared only after a hard refresh. I'm suspect that I still had the service worker registered (which is now 404).
