### ISSUE TITLE
Redirect View Source Conference Site URL

### ISSUE THREAD

**Issue by daniellevincent** [mdn/viewsourceconf#240]
Howdy -

We're refreshing the View Source site for this year's conference and need to direct the old URL to the new event URL.

Redirect https://viewsourceconf.org/  to https://events.mozilla.org/viewsource2018

We do not want to redirect the whole domain because we still have content that lives under the viewsourceconf.org domain

One other associated issue coming shortly.

**Comment by ejregithub** [comment]
@daniellevincent can you please indicate the specific date this redirect should be put into place?

**Comment by daniellevincent** [comment]
ASAP. Today, if possible. :)

**Comment by jpetto** [comment]
Just to clarify, we only want to redirect visitors that land on the home page, but not any other `viewsourceconf.org` URL?

**Comment by daniellevincent** [comment]
That is correct @jpetto

**Comment by jgmize** [comment]
https://viewsourceconf.org now redirects to https://events.mozilla.org/viewsource2018

**Comment by jgmize** [comment]
This was done manually by adding a metadata to the index.html via the s3 console with a key of Website-Redirect-Location and a value of https://events.mozilla.org/viewsource2018

**Comment by metadave** [comment]
Terraform should be updated: https://github.com/mozmeao/infra/blob/master/apps/viewsourceconf/tf/viewsourceconf.tf#L18

**Comment by daniellevincent** [comment]
Thank you!!! fantastic!

**Comment by jgmize** [comment]
@metadave the metadata change was applied at the object level, not the bucket level. I don't think the terraform needs to be updated.
