### ISSUE TITLE
Inconsistent ticket sale dates

### ISSUE THREAD

**Issue by kyoshino** [mdn/viewsourceconf#29]
https://viewsourceconf.org/ says

* Early Bird Registration: On sale until 10-09-2015
* Standard Registration: On sale until 11-03-2015

but https://ti.to/mdn/view-source-2015 says

* Early Bird Registration: On-sale until 30 September 2015
*  Regular Registration: On-sale through 1 November 2015

Which is correct?

**Comment by craigcook** [comment]
Clearing out resolved or no-longer-relevant issues.
