### ISSUE TITLE
Add Open Graph and Schema.org/Event meta data

### ISSUE THREAD

**Issue by kyoshino** [mdn/viewsourceconf#30]
I just tried to share the event page on Facebook and noticed that this site doesn't have any page image. http://schema.org/Event is also required for SEO.

**Comment by craigcook** [comment]
This is mostly no longer relevant. The static archive site does have a page image now, but still lacks Schema.org/Event data, which I suppose we could still add even though the event is in the past. Whatever we end up doing for the 2016 site (and beyond) we should certainly be sure it includes all the usual metadata goodness.
