### ISSUE TITLE
Stand up prod on both Deis clusters

### ISSUE THREAD

**Issue by hoosteeno** [mdn/viewsourceconf#37]
@jgmize It should pull from master tags.

**Comment by hoosteeno** [comment]
Uplifted from email:

@stephaniehobson says, "Does that setup have a default approach for asset caching? (ie. fonts and images)"

**Comment by jgmize** [comment]
> @stephaniehobson says, "Does that setup have a default approach for asset caching? (ie. fonts and images)"

No, we should add one to the [nginx.conf](https://github.com/mdn/viewsourceconf/blob/master/nginx.conf). Ideally we could set long-lived expires on all the assets and add hashes to the filenames. Perhaps we could use [metalsmith-fingerprint](https://github.com/christophercliff/metalsmith-fingerprint) for this?

**Comment by jgmize** [comment]
@hoosteeno tagged deploys to new "prod" apps have been auto-deploying since last week, but they will not be in production until the DNS switch. I know we were planning on switching tomorrow, but what time (including time zone) would you like me to make the switch?

**Comment by jgmize** [comment]
As discussed over IRC and email, the new production deployments went live at 11 AM CDT.
