### ISSUE TITLE
Turn off folder indexing on staging and prod

### ISSUE THREAD

**Issue by hoosteeno** [mdn/viewsourceconf#51]
This shouldn't work, right?

https://viewsourceconf-prod.us-west.moz.works/assets/

cc @jgmize

**Comment by jgmize** [comment]
Why shouldn't that work? I can disable it of course if you want, but given that all of the content on the site is available on the github repo as well I don't see any benefits to disabling directory listing.

**Comment by hoosteeno** [comment]
Fair enough. Disabling it is so second nature to me I guess, but yeah there aren't any secrets in this filesystem.
