### ISSUE TITLE
https://viewsourceconf.org/policies/ gives a 404.

### ISSUE THREAD

**Issue by bwinton** [mdn/viewsourceconf#70]
(as linked to from https://ti.to/mdn/view-source-seattle-2016)

**Comment by jgmize** [comment]
Thanks, the correct link should be https://viewsourceconf.org/code-of-conduct/ -- @hoosteeno can you fix the link on ti.to?

**Comment by jgmize** [comment]
Also, if we need to redirect `/policies/` to `/code-of-conduct/` we can add that to `nginx.conf`.

**Comment by hoosteeno** [comment]
Thanks! I'll try to get access to tito and change the link. If I can't we can redirect.

**Comment by hoosteeno** [comment]
This is fixed. Thanks again for catching it.
