### ISSUE TITLE
Optimize landing page for conference subpages

### ISSUE THREAD

**Issue by hoosteeno** [mdn/viewsourceconf#74]
We're going to change some layout, copy, and styles on the landing page to see if we can boost the number of people going to a conference subpage. Details:

* use the "bright" class on berlin/seattle buttons -- make them white
* make the copy on buttons bold
* make the top logo smaller -- 200px wide
* replace the main event text on the landing page:

>View Source is a conference for developers, by developers, where we explore best practices and exciting new techniques in web development and design. 
> 
> 1 track, 2 conference days, 16 amazing main stage speakers, lively breakout discussions, Q&A with industry experts, lightning talks, and just 500 available seats. 
> 
> Don't miss these View Source Conferences in 2016! 
>
> [In Europe, View Source will be held at the beautiful, riverfront Radialsystem in Berlin Mitte, September 12-14]. 
> 
> [In North America, View Source will be in downtown Seattle, November 1-3 at Benaroya Hall], home of the Seattle Symphony.

**Comment by stephaniehobson** [comment]
"1 track, 2 conference days" is not proper English. The "right" way to do it is to write out numbers that begin sentences or are less than ten. I don't know if this will a stand out to anyone but me.

I put "right" and "proper" in quotes because I know there are lots of good reasons to ignore the hoity toity rules of yore and one of the neat things about English is that we play with our "rules" all the time.

Before I code it though, I would like confirmation that the decision to contravene "proper" English grammar was intentional.

**Comment by stephaniehobson** [comment]
I'd like to make the links to the conference pages shorter so they are easier to read when skimming and give a clear indicator of what the user is likely to find on the associated page (ie, this is a link to the conference page, not the venue info). Is this okay?

> 
> In Europe, <a href="/berlin-2016/">View Source Berlin</a> will be held at the beautiful, riverfront Radialsystem, September 12-14.
> 
> In North America, <a href="/berlin-2016/">View Source Seattle</a> will be November 1-3 at Benaroya Hall, home of the Seattle Symphony.

**Comment by alispivak** [comment]
@stephaniehobson Agree with your changes.

So:
One track, two conference days, sixteen amazing main stage speakers, lively breakout discussions, Q&A with industry experts, lightening talks, and just five hundred available seats. 

and



In Europe, [View Source Berlin](https://github.com/berlin-2016/) will be held at the beautiful, riverfront Radialsystem, September 12-14.

In North America, [View Source Seattle](https://github.com/berlin-2016/) will be November 1-3 at Benaroya Hall, home of the Seattle Symphony.

**Comment by hoosteeno** [comment]
My only adjustment is "lightening" -> "lightning".

https://www.wordnik.com/words/lightening ⚡

**Comment by alispivak** [comment]
yes, typo

On Thu, May 26, 2016 at 12:00 PM, Justin Crawford <notifications@github.com>
wrote:

> My only adjustment is "lightening" -> "lightning".
>
> https://www.wordnik.com/words/lightening ⚡
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mdn/viewsourceconf/issues/74#issuecomment-221963355>
>



-- 
ali spivak
Head of Developer Marketing
aspivak@mozilla.com

**Comment by stephaniehobson** [comment]
PR #77 has been updated to reflect these changes. ⚡
